folio-org/mod-quick-marc

- src/main/java/org/folio/converter/QuickMarcToParsedRecordConverter.java
- src/test/java/org/folio/converter/QuickMarcToParsedRecordConverterTest.java
- src/test/java/org/folio/converter/TestUtils.java
Follow-up commit to [#24](https://github.com/folio-org/mod-quick-marc/pull/24) to caver particular case with indicators ["", ""].
> MODQM-16 - Incorrect saved record fields order

- README.md
- ramls/records-editor.raml
- src/main/java/org/folio/converter/QuickMarcToParsedRecordDtoConverter.java
- src/main/java/org/folio/rest/impl/RecordsEditorRecordsApi.java
- src/test/java/org/folio/rest/impl/QuickMarcApiTest.java
[MODQM-19](https://issues.folio.org/browse/MODQM-19) - quickMARC response status to 202 on record update
QuickMARC PUT /records-editor/records/{id} endpoint should return 202 status upon receiving the request
Changing of rail-contract, unit tests updating
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid …
> MODQM-19 - quickMARC response status to 202 on record update

- src/main/java/org/folio/converter/ParsedRecordDtoToQuickMarcConverter.java
- src/main/java/org/folio/converter/QuickMarcToParsedRecordDtoConverter.java
- src/main/java/org/folio/exception/ConverterException.java
- src/test/java/org/folio/rest/impl/QuickMarcApiTest.java
[MODQM-20](https://issues.folio.org/browse/MODQM-20) - quickMARC: ParsedRecordDto -> QuickMarcJson error handling
In order to customize converter's exceptions one need to return error with source of issue description instead of generic internal server error.
BE returns ConverterException with corresponding description if smith goes wrong with 006, 007, 008 fields.
- Do PRs exist for …
> MODQM-20 - quickMARC: ParsedRecordDto -> QuickMarcJson error handling

- .rancher-pipeline.yml
- Dockerfile
- Jenkinsfile
- pom.xml
[MODQM-26](https://issues.folio.org/browse/MODQM-26) - Migrate mod-quick-marc to JDK 11
Migrate quickMARC to JDK 11.
* Application is successfully builded on Java 11 platform
* Unit tests are completed without errors
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment. …
> MODQM-26 - Migrate mod-quick-marc to JDK 11

- descriptors/ModuleDescriptor-template.json
- src/main/java/org/folio/converter/Constants.java
- src/main/java/org/folio/rest/impl/RecordsEditorRecordsApi.java
- src/main/java/org/folio/util/ServiceUtils.java
- src/test/java/org/folio/rest/impl/QuickMarcApiTest.java
[MODQM-52](https://issues.folio.org/browse/MODQM-52) - Update MARC 005 field and send to SRS along with other quickMARC changes.
To have FOLIO update the MARC 005 field automatically whenever changes are made to the MARC record via quickMARC
Business logic for creation "timestamp" for updating field "005" was created.
Ideally all of the PRs involved in …
> MODQM-52 - Update MARC 005 field and send to SRS along with other quickMARC changes

- Jenkinsfile
See [FOLIO-2898](https://issues.folio.org/browse/FOLIO-2898) and https://dev.folio.org/guides/jenkinsfile/#back-end-modules
Use `doApiDoc` in Jenkinsfile. Replaces `publishAPI`.
> FOLIO-2898 Use new api-doc CI tool

- Dockerfile
Reinstate "USER folio" in Dockerfile
Reinstate user "folio" at the end of Dockerfile so that module runs on behalf of that user instead of "root"
> FOLSPRINGB-2 Reinstate 'USER folio' in Dockerfile

- pom.xml
- src/main/java/org/folio/qm/util/ChangeManagerPayloadUtils.java
- src/test/java/org/folio/qm/service/impl/MarcRecordsServiceImplTest.java
Update the RawRecordsDto payload based on the story - https://issues.folio.org/browse/MODQM-89
* used the latest released version of 'mod-source-record-manager'
* updated test to check that uuid is generated for the POST requests
> MODQM-89 - Update POST /jobExecutions/{jobExecutionId}/records payload with required fields

- Jenkinsfile
- descriptors/ModuleDescriptor-template.json
- pom.xml
- run-env.sh
- src/main/resources/application.yaml
Add admin health-check endpoint with Url: /admin/health
Utilize Sprint boot actuator health check. Replace standard path to /admin/health via app property. Enable health check in Jenkins settings
> MODQM-84 Add standard admin healthcheck endpoint

- lombok.config
Add lombok configuration file to tune coverage evaluation by skipping generated code
* add lombok.config to project's root folder with `lombok.addLombokGeneratedAnnotation` turned on
> Add lombok config

- src/main/java/org/folio/qm/controller/ErrorHandling.java
- src/test/java/org/folio/qm/controller/RecordsEditorRecordsApiTest.java
FeignException handler currently expects exceptions with status code. In cases when FeignException is thrown due to connection timeout there is no status code in exception.
> MODQM-97 Fix FeignException handler

- pom.xml
Reverts folio-org/mod-quick-marc#88
> Revert "Bump openapi-generator-maven-plugin from 4.3.1 to 5.1.0"

- src/main/java/org/folio/qm/converter/ParsedRecordDtoToQuickMarcConverter.java
- src/test/java/org/folio/qm/conveter/ParsedRecordDtoToQuickMarcConverterTest.java
- src/test/java/org/folio/qm/utils/testentities/TestEntitiesUtils.java
- src/test/resources/mockdata/change-manager/parsedRecordDtoUnsorted.json
Sort fields by tag code before responding on GET /record.
Add integer comparator to sort fields in srm-to-qm converter
> MODQM-126 Sort fields by tag code

- src/main/java/org/folio/qm/config/KafkaConfig.java
- src/main/java/org/folio/qm/controller/QmTenantController.java
- src/main/java/org/folio/qm/messaging/topic/KafkaTopicsInitializer.java
- src/test/java/org/folio/qm/controller/BaseApiTest.java
Fix the problem when Kafka listeners didn't subscribe to topics on module initialization
* Create Kafka topics on tenant initialization
* Reload Kafka endpoint registry after topic created.
> MODQM-145 Fix Kafka listeners not subscribed

- src/main/java/org/folio/qm/messaging/deserializer/DataImportEventDeserializer.java
- src/test/java/org/folio/qm/controller/BaseApiTest.java
Quick MARC can't deserialize event from data import. Data import no longer uses the zip mechanism.
removed unzipping from DataImportEventDeserializer
https://issues.folio.org/browse/MODQM-162
> MODQM-162 Can't deserialize events from data import

- NEWS.md
- src/main/java/org/folio/qm/controller/ErrorHandling.java
- src/main/java/org/folio/qm/messaging/listener/QuickMarcEventListener.java
- src/main/resources/swagger.api/records-editor-async.yaml
- src/test/java/org/folio/qm/controller/RecordsEditorAsyncApiTest.java
Update of record returns 409  status if optimistic locking error occurred.
* Add to API with 409 status
* Add logging for unexpected errors
* Detect optimistic error message
> MODQM-178 Update return 409 if optimistic locking error

- NEWS.md
- pom.xml
Fix log4j2 RCE vulnerability
log4j2 version set to 2.16.0
https://issues.folio.org/browse/MODQM-181
> MODQM-181 Kiwi R3 2021 - Log4j vulnerability verification and correction

- descriptors/ModuleDescriptor-template.json
In the scope of the [PR](https://github.com/folio-org/mod-source-record-manager/pull/530/commits/8089c6aa8e42ca7d63d3c8990128eb1cffabdc18)  the query parameters for `GET /metadata-provider/jobExecutions` endpoint were changed, so 
"source-manager-job-executions" interface version will be increased: from 2.0 to 3.0. It is necessary to update interface dependency
* update "source-manager-job-executions" interface version from 2.0 to 3.0
##
> Update source-manager-job-executions interface version

- pom.xml
- src/test/java/org/folio/qm/controller/BaseApiTest.java
- src/test/java/org/folio/qm/controller/RecordsEditorApiTest.java
- src/test/java/org/folio/qm/controller/RecordsEditorAsyncApiTest.java
- src/test/java/org/folio/qm/utils/APITestUtils.java
In quick-marc some tests are written with RestAssured lib and other with Spring MockMVC. The purpose is to rewrite all tests to Spring MockMVC and remove the RestAssured dependency.
> MODQM-187 Rewrite tests from RestAssured to Spring MockMVC

- src/main/java/org/folio/qm/messaging/listener/QuickMarcEventListener.java
- src/main/java/org/folio/qm/service/impl/DataImportEventProcessingServiceImpl.java
- src/main/java/org/folio/qm/service/impl/DeferredResultCacheService.java
- src/test/java/org/folio/qm/controller/RecordsEditorAsyncApiTest.java
Not evicting result causing that Spring returns to controller not actual DeferredResult
Evict DeferredResult after result was set
> MODQM-222 Evict DeferredResult after result was set

- src/main/java/org/folio/qm/converter/elements/Constants.java
- src/main/java/org/folio/qm/service/impl/DefaultValuesPopulationService.java
- src/main/java/org/folio/qm/service/impl/MarcRecordsServiceImpl.java
- src/main/java/org/folio/qm/service/population/LeaderMarcPopulationService.java
- src/main/java/org/folio/qm/service/population/MarcPopulationService.java
- src/main/java/org/folio/qm/service/population/impl/HoldingsLeaderMarcPopulationService.java
- src/test/java/org/folio/qm/service/population/LeaderMarcPopulationServiceTest.java
- src/test/java/org/folio/qm/service/population/impl/HoldingsLeaderMarcPopulationServiceTest.java
- src/test/java/org/folio/qm/service/population/impl/LeaderMarcPopulationServiceTest.java
Edit MARC holdings record: When a SRS holdings Leader field contains invalid values for the positions that have only one possible value then update the leader positions with the valid values upon user hitting Save
- add filling leader positions with default values before validation on create/update
[MODQM-226](https://issues.folio.org/browse/MODQM-226)
> MODQM-226 Improve handling of erroneous MARC holdings Leader positions that cannot be edited via quickMARC

- src/main/java/org/folio/qm/service/population/impl/BibliographicLeaderMarcPopulationService.java
- src/test/java/org/folio/qm/service/population/impl/BibliographicLeaderMarcPopulationServiceTest.java
Edit MARC Bib record: When a SRS bib Leader field contains invalid values for the positions: 00-04, 10-11, 12-16, 20-23 then update the leader positions with the valid values upon user hitting Save
[MODQM-225](https://issues.folio.org/browse/MODQM-225)
> MODQM-225 Improve handling of erroneous MARC bib Leader positions that cannot be edited via quickMARC

- src/main/java/org/folio/qm/converter/elements/Constants.java
- src/main/java/org/folio/qm/converter/elements/LeaderItem.java
- src/main/java/org/folio/qm/service/population/LeaderMarcPopulationService.java
- src/main/java/org/folio/qm/service/population/impl/AuthorityLeaderMarcPopulationService.java
- src/main/java/org/folio/qm/service/population/impl/BibliographicLeaderMarcPopulationService.java
- src/main/java/org/folio/qm/service/population/impl/HoldingsLeaderMarcPopulationService.java
- src/test/java/org/folio/qm/service/population/LeaderMarcPopulationServiceTest.java
- src/test/java/org/folio/qm/service/population/impl/AuthorityLeaderMarcPopulationServiceTest.java
- src/test/java/org/folio/qm/service/population/impl/BibliographicLeaderMarcPopulationServiceTest.java
Edit MARC authority record: When a SRS authority Leader field contains invalid values for the positions listed in the below table then update the leader positions with the valid values upon user hitting Save
[MODQM-229](https://issues.folio.org/browse/MODQM-229)
> MODQM-229 Improve handling of erroneous MARC authority Leader positions that cannot be edited via quickMARC

- src/main/java/org/folio/qm/converter/elements/Constants.java
- src/main/java/org/folio/qm/converter/field/dto/Tag008BibliographicControlFieldConverter.java
- src/main/java/org/folio/qm/validation/impl/common/LeaderMatch008RecordValidationRule.java
- src/test/java/org/folio/qm/controller/RecordsEditorAsyncApiTest.java
- src/test/java/org/folio/qm/support/utils/testdata/Tag008FieldTestData.java
On MARC field 008 > remove the ELvl byte if it is only present because it is Leader 17 position field
Make sure that Leader position 17 accepts the values noted for Leader position 17 as outlined https://issues.folio.org/browse/MODQM-164
JIRA: https://issues.folio.org/browse/MODQM-253
- Remove validation of Elvl in 008 tag
- Remove Elvl from DTO converter
> MODQM-253 Changes to Leader position 17 validation AND 008 byte

- src/main/java/org/folio/qm/client/UsersClient.java
- src/test/java/org/folio/qm/controller/RecordsEditorIT.java
Fix error with retrieving record when updatedBy user is not found.
JIRA: https://issues.folio.org/browse/MODQM-267
- Update UsersClient to decode 404
- Add test
> MODQM-267 Back-end: Cannot access a MARC bib record because creator has been deleted

- NEWS.md
- doc/RELEASES.md
- pom.xml
Prepare for next development iteration
[MODQM-290](https://issues.folio.org/browse/MODQM-290)
Release branch `release/v2.5` was created separately from branch `tmp-release-v2.5` with excluded bib-authority linking feature
> Tmp prepare dev v2.6

- src/main/java/org/folio/qm/converter/field/dto/AuthorityDataFieldConverter.java
- src/main/java/org/folio/qm/converter/field/dto/CommonDataFieldConverter.java
- src/main/java/org/folio/qm/util/MarcUtils.java
- src/test/java/org/folio/qm/converter/field/dto/AuthorityDataFieldConverterTest.java
- src/test/java/org/folio/qm/converter/field/dto/CommonDataFieldConverterTest.java
- src/test/java/org/folio/qm/util/MarcUtilsTest.java
If any "MARC" record has "$9" subfield in any field in "invalid UUID format" user can't open this "MARC" record. The "500" error is displayed.
_Invalid authority UUIDs can be skipped during GET request_
https://issues.folio.org/browse/MODQM-296
> MODQM-296 - $9 with value in "invalid UUID format" leads to "500" error in SRS

- src/main/java/org/folio/qm/converter/field/dto/BibliographicDataFieldConverter.java
- src/main/java/org/folio/qm/converter/field/dto/CommonDataFieldConverter.java
- src/test/java/org/folio/qm/converter/field/dto/BibliographicDataFieldConverterTest.java
- src/test/java/org/folio/qm/converter/field/dto/CommonDataFieldConverterTest.java
Fix processing of authority links
Links should be processed only for bibliographic fields, not authority fields
> MODQM-304 Fix processing of authority links

- pom.xml
- src/main/java/org/folio/qm/client/LinksClient.java
- src/main/java/org/folio/qm/service/impl/LinksServiceImpl.java
- src/main/resources/swagger.api/schemas/fieldItem.json
- src/test/java/org/folio/qm/service/impl/LinksServiceImplTest.java
Add linkingRuleId to request/response bodies
* Update request/response bodies with linkingRuleId
> MODQM-314 Add linkingRuleId to request/response bodies

- NEWS.md
- src/main/java/org/folio/qm/converter/elements/LeaderItem.java
- src/test/java/org/folio/qm/validation/leader/BibliographicLeaderValidationRuleTest.java
Support MARC LDR_19 values 'b' and 'c' for MARC bib
- add 'b' and 'c' to validation rule of bib's 19'th position
[MODQM-315](https://issues.folio.org/browse/MODQM-315)
> MODQM-315 BE - Edit/Derive a MARC bib - Support MARC LDR_19 values 'b' and 'c'

- src/main/java/org/folio/qm/client/LinkingRulesClient.java
- src/main/java/org/folio/qm/client/LinksClient.java
- src/main/java/org/folio/qm/service/LinkingRulesService.java
- src/main/java/org/folio/qm/service/impl/LinkingRulesServiceImpl.java
- src/test/java/org/folio/qm/service/impl/LinksServiceImplTest.java
- src/test/java/org/folio/qm/support/utils/ApiTestUtils.java
Fix opening bib records in quick marc
- Fix url for linking rules
[MODQM-323](https://issues.folio.org/browse/MODQM-323)
> MODQM-323 Can't open imported "MARC Bib" record in "quickmarc"

- pom.xml
Migrate to folio-spring-support v7.0.0
If the module is not required to have CQL support then just update folio-spring-base dependency to v7.0.0 
If the module is required to have CQL support:
1. update folio-spring-base dependency to v7.0.0 
2. add new dependency
`<dependency>
<groupId>org.folio</groupId>
<artifactId>folio-spring-cql</artifactId>
<version>7.0.0</version>
</dependency> `
3. Change usage of `findByCQL` method to `findByCql` 
Because module is not required to have CQL support, only **folio-spring-base** dependency updated
[MODQM-336](https://issues.folio.org/browse/MODQM-336)
> MODQM-336: Migrated folio-spring-base to v7.0.0

- src/main/java/org/folio/qm/converter/field/qm/Tag008BibliographicFieldItemConverter.java
- src/main/java/org/folio/qm/converter/field/qm/Tag008FieldItemConverter.java
- src/main/java/org/folio/qm/converter/field/qm/Tag008HoldingsFieldItemConverter.java
- src/test/java/org/folio/qm/converter/field/dto/Tag008BibliographicControlFieldConverterTest.java
- src/test/java/org/folio/qm/converter/field/qm/Tag008BibliographicFieldItemConverterTest.java
- src/test/java/org/folio/qm/converter/field/qm/Tag008HoldingsFieldItemConverterTest.java
- src/test/java/org/folio/qm/support/utils/testdata/Tag008FieldTestData.java
Given user creates/edits/derives a MARC record. AND a 008 is added.
When user hits Save.
Then the first six positions (00-05) - Date entered on file must be 1.) system populated with the date the user created the record OR in cases of edit when user added the 008 field. 2.) this value should never change per MARC documentation. 3.) Populate in this format yymmdd is yy for the year, mm for the month, and dd for the day.
- Add 'Entered' date filling to `Tag008BibliographicFieldItemConverter`
- Add 'Entered' date filling to `Tag008HoldingsFieldItemConverter`
[MODQM-341](https://issues.folio.org/browse/MODQM-341)
> MODQM-341 Set 'entered' date when empty on 008 field for bibs/holdings

- src/main/java/org/folio/qm/converter/field/qm/Tag008FieldItemConverter.java
- src/test/java/org/folio/qm/converter/field/dto/Tag008BibliographicControlFieldConverterTest.java
- src/test/java/org/folio/qm/support/utils/testdata/Tag008FieldTestData.java
In previous PR "empty date filling" was implemented. This PR continues task and brings "invalid date correction"
[MODQM-341](https://issues.folio.org/browse/MODQM-341)
- Add 'Entered' date correction to `Tag008FieldItemConverter`
"abcdef" for "Entered" in test data was changed to "123456" because now converter changes invalid (alphabetic) value to a valid one
> MODQM-341 Set 'entered' date when invalid on 008 field

- src/main/java/org/folio/qm/converter/field/qm/Tag008AuthorityFieldItemConverter.java
- src/test/java/org/folio/qm/converter/field/dto/Tag008BibliographicControlFieldConverterTest.java
- src/test/java/org/folio/qm/converter/field/qm/Tag008AuthorityFieldItemConverterTest.java
- src/test/java/org/folio/qm/converter/field/qm/Tag008BibliographicFieldItemConverterTest.java
- src/test/java/org/folio/qm/support/utils/testdata/Tag008FieldTestData.java
Populate/fix "Date entered" in 008 field for authorities
[MODQM-346](https://issues.folio.org/browse/MODQM-346)
- Add 'Entered' date population/correction to `Tag008AuthorityFieldItemConverter`
> fix(field-system-population): Set 'entered' date when absent/invalid on 008 field for authorities

- .github/workflows/api-doc.yml
- .github/workflows/api-lint.yml
- .github/workflows/api-schema-lint.yml
- Jenkinsfile
- README.md
- src/main/resources/swagger.api/records-editor.yaml
[FOLIO-3678](https://issues.folio.org/browse/FOLIO-3678)
Use GitHub Workflows for [api-lint](https://dev.folio.org/guides/api-lint/) and [api-schema-lint](https://dev.folio.org/guides/describe-schema/) and [api-doc](https://dev.folio.org/guides/api-doc/)
(instead of Jenkins-operated CI stages).
> FOLIO-3678 MODQM-350 Use GitHub Workflows api-lint and api-schema-lint and api-doc

- .run/Tests-Integration.run.xml
- .run/Tests-Unit.run.xml
- NEWS.md
- pom.xml
- src/main/java/org/folio/qm/converter/field/qm/AbstractFieldItemConverter.java
- src/main/java/org/folio/qm/mapper/LinksSuggestionsMapper.java
- src/main/java/org/folio/qm/util/MarcUtils.java
- src/test/java/org/folio/qm/mapper/LinksSuggestionsMapperTest.java
Fix record convertion that causes missing subfields in response
- utilize common logic for string-to-subfields parsing
https://issues.folio.org/browse/MODQM-358
> fix(automate-linking): missing subfields in response

- pom.xml
- src/main/java/org/folio/qm/domain/entity/JobProfile.java
- src/main/java/org/folio/qm/domain/entity/MarcSpecification.java
- src/main/java/org/folio/qm/domain/entity/RecordCreationStatus.java
Update hypersistence-utils-hibernate to new version
Update defining enums in enttities to use library above
Update spring version to the latest
> fix: update hypersistence dependency to supported by Hibernate 6.2

- NEWS.md
- descriptors/ModuleDescriptor-template.json
- src/main/java/org/folio/qm/converter/elements/ControlFieldItem.java
- src/test/java/org/folio/qm/support/utils/testdata/Tag006FieldTestData.java
- src/test/java/org/folio/qm/support/utils/testdata/Tag008FieldTestData.java
There is an error in marc specification for item Projection (006/05-06) which is a part of maps specification for 008 field. Currently this item works like an array of values and should be a string. Change also will be done for 006 field because Projection item definition is common for 008 and 006.
Change the item type from an array to a string for Proj MAPS item. (isArray=false)
- change interface version
- update unit tests
- update NEWS
https://folio-org.atlassian.net/browse/MODQM-406
https://folio-org.atlassian.net/browse/UIQM-636
> MODQM-406 Change item type from an array to a string for 008 field

- NEWS.md
- pom.xml
do not delete kafka topics if tenant collection topic feature is enabled
Update to newest folio-service-tools
https://folio-org.atlassian.net/browse/MODQM-423
> fix: do not delete kafka topics if tenant collection topic feature is enabled

- NEWS.md
- src/main/java/org/folio/qm/converter/MarcFieldsConverter.java
- src/main/java/org/folio/qm/converter/MarcFieldsHardConverter.java
- src/main/java/org/folio/qm/converter/MarcFieldsSoftConverter.java
- src/main/java/org/folio/qm/converter/MarcQmToMarcRecordConverter.java
- src/main/java/org/folio/qm/converter/field/FieldItemConverter.java
- src/main/java/org/folio/qm/converter/field/qm/AbstractFieldItemConverter.java
- src/main/java/org/folio/qm/mapper/LinksSuggestionsMapper.java
- src/main/java/org/folio/qm/util/MarcUtils.java
- src/test/java/org/folio/qm/controller/RecordsEditorIT.java
- src/test/java/org/folio/qm/controller/SpecificationKafkaListenerIT.java
- src/test/java/org/folio/qm/converter/MarcFieldsConverterTest.java
- src/test/java/org/folio/qm/converter/MarcFieldsSoftConverterTest.java
- src/test/java/org/folio/qm/converter/MarcQmToMarcRecordConverterTest.java
- src/test/java/org/folio/qm/converter/field/qm/CommonFieldItemConverterTest.java
- src/test/java/org/folio/qm/util/MarcUtilsTest.java
- src/test/resources/mockdata/response/quickMarcValidate.json
- src/test/resources/mockdata/response/specifications/specification.json
- src/test/resources/mockdata/response/specifications/specificationById.json
Don't throw an exception on empty field content during record conversion
Add soft conversion move for converting user record to quick MARC record so invalid content could be validated using record specification
[MODQM-438](https://folio-org.atlassian.net/browse/MODQM-438)
Verified on Rancher
> fix(validation): Don't throw an exception on empty field content during record convertion

- NEWS.md
- src/main/java/org/folio/qm/converter/MarcQmToMarcRecordConverter.java
- src/test/java/org/folio/qm/converter/MarcQmToMarcRecordConverterTest.java
Convert empty spaces values to '#'
Add replacement for empty spaces inside quick marc to marc record converter fro indicators
[MODQM-443](https://issues.folio.org/browse/MODQM-443)
> Update quick marc converter to convert indicator's empty spaces

- NEWS.md
- src/main/java/org/folio/qm/converter/MarcQmToMarcRecordConverter.java
- src/main/java/org/folio/qm/service/impl/ValidationServiceImpl.java
- src/test/java/org/folio/qm/converter/MarcQmToMarcRecordConverterTest.java
- src/test/java/org/folio/qm/service/impl/ValidationServiceImplTest.java
Use '#' for indicators validation internally while using ' ' or '\\' on UI side
[MODQM-443](https://folio-org.atlassian.net/browse/MODQM-443)
> feat(validation): Replace spaces with '\' instead of '#' in indicator codes

- src/main/java/org/folio/qm/converter/MarcQmToMarcRecordConverter.java
- src/test/java/org/folio/qm/controller/RecordsEditorIT.java
- src/test/java/org/folio/qm/support/utils/testentities/TestEntitiesUtils.java
- src/test/resources/mockdata/response/quickMarcSubfieldValidate.json
- src/test/resources/mockdata/response/specifications/specification.json
[MODQM-446](https://folio-org.atlassian.net/browse/MODQM-446) Exclude processing of empty/blank subfields in the MarcQmToMarcRecordConverter converter as this affects the validation result in the mod-record-specifications.
Exclude processing of empty/blank subfields in the MarcQmToMarcRecordConverter converter.
> feat(subfield-converter) exclude processing of empty/blank subfields in the MarcQmToMarcRecordConverter converter

- NEWS.md
- src/main/java/org/folio/qm/service/impl/ValidationServiceImpl.java
- src/test/java/org/folio/qm/service/impl/ValidationServiceImplTest.java
Return '\' instead '#' in validation message for undefined indicator rule
Modify message for specific code
https://folio-org.atlassian.net/browse/MODQM-448
> fix(validation): return '\' instead '#' in validation message for undefined indicator rule
