folio-org/mod-quick-marc

- README.md
Use initial year of creation in README
In subsequent years, use range of years.
> FOLIO-360 Use initial year of creation in README

- README.md
- ramls/examples/quick_marc_json.sample
- ramls/records-editor.raml
- ramls/schemas/quick_marc_json.json
[MODQM-1](https://issues.folio.org/browse/MODQM-1) - UI-compatible json schema for MARC record
In order to support displaying MARC record on QuickMARC editor one need to create corresponding schema for UI acceptable MARC records representation.
* json schema and sample created
* RAML file created
* validated with [liquid-technologies.com](https://www.liquid-technologies.com/online-json-schema-validator)
- Are the JIRAs under …
> MODQM-1 - UI-compatible json schema for MARC record

- README.md
- descriptors/ModuleDescriptor-template.json
- ramls/records-editor.raml
- src/main/java/org/folio/rest/impl/RecordsEditorRecordsImpl.java
Follow-up PR to [PR#6](https://github.com/folio-org/mod-quick-marc/pull/6) with rail's contract updating in accordance to new requirement.
> MODQM-3 - Stub for GET QuickMarcRecord

- descriptors/ModuleDescriptor-template.json
Follow-up commit to integrate with SRS [PR#5](https://github.com/folio-org/mod-quick-marc/pull/5)
> MODQM-3 - Implement GET records-editor/records endpoint

- src/main/java/org/folio/rest/impl/RecordsEditorRecordsImpl.java
- src/test/java/org/folio/rest/impl/QuickMarcApiTest.java
[MODQM-4](https://issues.folio.org/browse/MODQM-4) (Stubbed) 
* Fixed PUT validation
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team dependencies increase. …
> MODQM-4 (Stubbed) - Fixed PUT validation

- ramls/schemas/quick_marc_json.json
- src/main/java/org/folio/rest/impl/RecordsEditorRecordsApi.java
- src/main/java/org/folio/service/ChangeManagerService.java
- src/test/java/org/folio/rest/impl/QuickMarcApiTest.java
[MODQM-4](https://issues.folio.org/browse/MODQM-4) - Implement PUT records-editor/marc-records/id
* minor fixes
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team …
> MODQM-4 - Implement PUT records-editor/marc-records/id

- pom.xml
[MODQM-15](https://issues.folio.org/browse/MODQM-15) - mod-quick-marc: Update to RMB v30
Update RMB to v30.0.0
Update RMB and Vert.X version in the pom.xml
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially …
> MODQM-15 - mod-quick-marc: Update to RMB v30

- README.md
[MODQM-18](https://issues.folio.org/browse/MODQM-18) - Update reference to data-import-raml-storage
Updating of the reference to the actual data-import-raml-storage schemas
Updating of the schemas reference
Should be merged along with
https://github.com/folio-org/data-import-processing-core/pull/53
https://github.com/folio-org/mod-data-import-converter-storage/pull/109
https://github.com/folio-org/mod-source-record-storage/pull/161
https://github.com/folio-org/mod-source-record-manager/pull/290
https://github.com/folio-org/mod-data-import/pull/121
If there are breaking changes, please **STOP** and …
> MODQM-18 - Update reference to data-import-raml-storage

- NEWS.md
- descriptors/ModuleDescriptor-template.json
- pom.xml
> MODQM-14 - Release 1.0.0

- NEWS.md
- pom.xml
- ramls/records-editor.raml
[MODQM-30](https://issues.folio.org/browse/MODQM-30) - Release 1.1.0
> MODQM-30 - Release 1.1.0

- .rancher-pipeline.yml
Rancher pipeline configuration for mod-quick-marc.
+ @celticmask
> Rancher pipeline for mod-quick-marc

- pom.xml
[MODQM-31](https://issues.folio.org/browse/MODQM-31) - mod-quick-marc: RMB Update
Update RMB to version 30.2.7
* RMB updated
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and …
> MODQM-31 - mod-quick-marc: RMB Update

- .rancher-pipeline.yml
- pom.xml
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team dependencies increase.  
While it's helpful for reviewers to help identify potential problems, ensuring that it's …
> Rancher fixed Java version

- NEWS.md
- pom.xml
[MODQM-32](https://issues.folio.org/browse/MODQM-32) Release - 1.2.0
> MODQM-32 - Release 1.2.0

- NEWS.md
[MODQM-50](https://issues.folio.org/browse/MODQM-50) - Bug fix release 1.2.1
> MODQM-50 - Release 1.2.1

- NEWS.md
[MODQM-50](https://issues.folio.org/browse/MODQM-50) - Bug fix release 1.2.1
Updating NEWS.md in the master branch
> MODQM-50 - Release 1.2.1 (Updating NEWS.md in the master branch)

- NEWS.md
[MODQM-51](https://issues.folio.org/browse/MODQM-51) - Bug fix release 1.2.2
> MODQM-51 - Release 1.2.2 (backport to master)

- PERSONAL_DATA_DISCLOSURE.md
Place a copy of the personal data disclosure form at the top level of the module github repository to disclose stored types of personal data
Added PERSONAL_DATA_DISCLOSURE.md file
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to …
> MODQM-56 - Add personal data disclosure form

- README.md
- descriptors/ModuleDescriptor-template.json
- pom.xml
- ramls/records-editor.raml
- src/main/java/org/folio/qm/client/SRMChangeManagerClient.java
- src/main/java/org/folio/qm/controller/RecordsEditorRecordsApi.java
- src/main/resources/swagger.api/records-editor.yaml
- src/test/java/org/folio/qm/controller/BaseApiTest.java
- src/test/java/org/folio/qm/controller/RecordsEditorRecordsApiTest.java
As a part of duplicate a MARC bibliographic record feature this merge request(https://issues.folio.org/browse/MODQM-77) aimed to create a stub endpoint to POST already existing MARC record to be duplicated via "source-record-manager" module. The further implementation is planned in https://issues.folio.org/browse/MODQM-80
* introduced new endpoint POST /records-editor/records in ModuleDescriptor, raml and yaml files
* added stub implementation with Response status 501 - NOT_IMPLEMENTED
* added test
* updated README file
- …
> MODQM-77 - Support stub endpoint duplicate a MARC bibliographic record

- src/main/java/org/folio/qm/controller/ErrorHandling.java
- src/main/java/org/folio/qm/service/ValidationService.java
- src/main/java/org/folio/qm/service/impl/MarcRecordsServiceImpl.java
- src/main/java/org/folio/qm/service/impl/ValidationServiceImpl.java
- src/main/java/org/folio/qm/util/ErrorUtils.java
- src/test/java/org/folio/qm/controller/RecordsEditorRecordsApiTest.java
Change response for errors:
* qmRecordId is invalid UUID
* qmRecordId is empty
> MODQM-78 Change errors responses

- descriptors/ModuleDescriptor-template.json
* Add interfaces to `requires` section
* Add missed permission
> MODQM-83 Add interfaces to requires section

- src/main/java/org/folio/qm/service/impl/MarcRecordsServiceImpl.java
- src/test/java/org/folio/qm/service/impl/MarcRecordsServiceImplTest.java
- src/test/java/org/folio/qm/utils/TestUtils.java
- src/test/resources/mockdata/quick-marc-json/quickMarcJson_emptyContent.json
fix for https://issues.folio.org/browse/MODQM-85
* remove empty fields
> MODQM-85 - Could not Derive a new MARC bib record

- README.md
And verify updated api-doc and api-lint tools, and updated jenkins build image.
> FOLIO-1021 Use range for copyright years

- descriptors/ModuleDescriptor-template.json
Due to changes made in scope of https://issues.folio.org/browse/MODQM-110 interfaces version should be updated to notify dependant modules about changes. 
* updated interface version for "source-manager-job-executions", "source-manager-records" from 1.0 to 3.0
> MODQM-114 - Update interface version

- src/main/java/org/folio/qm/converter/elements/ControlFieldItem.java
- src/test/resources/mockdata/quick-marc-json/maps.json
Fix 006/Proj bytes handling. It should be an array instead of 2-char string.
> MODQM-124 Fix 006/Proj handling

- pom.xml
- src/main/java/org/folio/qm/config/KafkaConfig.java
- src/main/java/org/folio/qm/controller/RecordsEditorRecordsApi.java
- src/main/java/org/folio/qm/exception/ExternalException.java
- src/main/java/org/folio/qm/messaging/deserializer/QmCompletedEventDeserializer.java
- src/main/java/org/folio/qm/messaging/domain/QmCompletedEventPayload.java
- src/main/java/org/folio/qm/messaging/listener/QuickMarcEventListener.java
- src/main/java/org/folio/qm/messaging/listener/providers/GroupIdProvider.java
- src/main/java/org/folio/qm/messaging/listener/providers/GroupIdProviderImpl.java
- src/main/java/org/folio/qm/messaging/listener/providers/TopicPatternProvider.java
- src/main/java/org/folio/qm/messaging/listener/providers/TopicPatternProviderImpl.java
- src/main/java/org/folio/qm/service/CacheService.java
- src/main/java/org/folio/qm/service/impl/CacheServiceImpl.java
- src/main/resources/swagger.api/records-editor-async.yaml
- src/main/resources/swagger.api/records-editor.yaml
- src/test/java/org/folio/qm/controller/BaseApiTest.java
- src/test/java/org/folio/qm/controller/KafkaListenerApiTest.java
- src/test/java/org/folio/qm/controller/RecordsEditorAsyncApiTest.java
- src/test/java/org/folio/qm/controller/RecordsEditorRecordsApiTest.java
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team dependencies increase.  
While it's helpful for reviewers to help identify potential problems, ensuring that it's …
> Test deffered result

- src/main/java/org/folio/qm/service/impl/CacheServiceImpl.java
- src/main/resources/application.yaml
Make CacheService configurable
* add expiration time
* move cache values to configuration
> MODQM-138 Make CacheService configurable

- NEWS.md
- src/main/java/org/folio/qm/converter/elements/LeaderItem.java
- src/main/java/org/folio/qm/converter/impl/MarcHoldingsDtoConverter.java
- src/main/java/org/folio/qm/service/impl/ValidationServiceImpl.java
- src/main/java/org/folio/qm/validation/LeaderValidationRule.java
- src/main/java/org/folio/qm/validation/impl/bibliographic/BibliographicLeaderValidationRule.java
- src/main/java/org/folio/qm/validation/impl/holdings/HoldingsLeaderValidationRule.java
- src/test/java/org/folio/qm/validation/leader/BibliographicLeaderValidationRuleTest.java
- src/test/java/org/folio/qm/validation/leader/CommonLeaderValidationRuleTest.java
- src/test/java/org/folio/qm/validation/leader/HoldingsLeaderValidationRuleTest.java
- src/test/resources/mockdata/change-manager/parsedRecordHoldingsDto.json
- src/test/resources/mockdata/change-manager/parsedRecordHoldingsDtoRestored.json
- src/test/resources/mockdata/quick-marc-json/quickMarcHoldings.json
- src/test/resources/mockdata/quick-marc-json/quickMarcHoldings_edited.json
Marc holdings leader rules
create validator for leader
https://issues.folio.org/browse/MODQM-151
> MARC holdings - Leader rules

- src/main/java/org/folio/qm/converter/elements/LeaderItem.java
- src/main/java/org/folio/qm/validation/LeaderValidationRule.java
- src/main/java/org/folio/qm/validation/impl/bibliographic/BibliographicLeaderValidationRule.java
- src/test/java/org/folio/qm/validation/leader/BibliographicLeaderValidationRuleTest.java
Fix leader validation rule
* remove validation for 17 position of leader for bib-records.
> MODQM-164 Fix leader validation rule

- NEWS.md
- descriptors/ModuleDescriptor-template.json
- src/main/java/org/folio/qm/validation/LeaderValidationRule.java
- src/main/java/org/folio/qm/validation/impl/authority/AuthorityLeaderValidationRule.java
- src/main/java/org/folio/qm/validation/impl/bibliographic/BibliographicLeaderValidationRule.java
- src/main/java/org/folio/qm/validation/impl/holdings/HoldingsLeaderValidationRule.java
- src/main/resources/swagger.api/schemas/marcFormat.json
- src/test/java/org/folio/qm/validation/leader/AuthorityLeaderValidationRuleTest.java
- src/test/java/org/folio/qm/validation/leader/BibliographicLeaderValidationRuleTest.java
- src/test/java/org/folio/qm/validation/leader/CommonLeaderValidationRuleTest.java
- src/test/java/org/folio/qm/validation/leader/HoldingsLeaderValidationRuleTest.java
Marc authority leader rules
Add leader validator for authority
[MODQM-154](https://issues.folio.org/browse/MODQM-154)
> MODQM-154: MARC Authority - Leader rules

- src/main/java/org/folio/qm/service/impl/RecordCreationServiceImpl.java
Fix error during creation record via quick marc
Change verification from MapStruct package to StringUtils
https://issues.folio.org/browse/MODQM-174
> MODQM-174 Derive MARC bib record failed

- src/main/java/org/folio/qm/converter/AbstractMarcQmConverter.java
- src/test/java/org/folio/qm/conveter/MarcHoldingsQmConverterTest.java
MODQM-180 Fix NPE in converter
> MODQM-180 Fix NPE in converter

- NEWS.md
- pom.xml
> Release 2.2.2

- NEWS.md
- pom.xml
> Release 2.1.2

- descriptors/ModuleDescriptor-template.json
need to extend gui quickmarc editor permissions to "converter-storage.field-protection-settings.get"
add dependent interface
add module permission to GET endpoint
[MODQM-201](https://issues.folio.org/browse/MODQM-201)
> MODQM-201 add quickmarc permissions

- src/main/java/org/folio/qm/controller/RecordsEditorAsyncApiImpl.java
- src/test/java/org/folio/qm/controller/RecordsEditorAsyncApiTest.java
Fix record second updating
[MODQM-213](https://issues.folio.org/browse/MODQM-213)
> MODQM-213 MARC authority - Cannot Edit record (snapshot environment)

- src/main/java/org/folio/qm/controller/ErrorHandling.java
- src/main/java/org/folio/qm/messaging/listener/QuickMarcEventListener.java
- src/main/java/org/folio/qm/service/impl/DeferredResultCacheService.java
- src/test/java/org/folio/qm/controller/RecordsEditorAsyncApiTest.java
Fix OL handling and improve timeout handling
> MODQM-218 Fix OL handling and improve timeout handling

- descriptors/ModuleDescriptor-template.json
Add module permission
https://issues.folio.org/browse/MODQM-227
> MODQM-227 User with permission "MARC Authority: Delete MARC authority record" can't delete authority record

- src/main/java/org/folio/qm/converter/elements/Constants.java
- src/main/java/org/folio/qm/converter/elements/LeaderItem.java
- src/main/java/org/folio/qm/service/population/LeaderMarcPopulationService.java
- src/test/java/org/folio/qm/service/population/LeaderMarcPopulationServiceTest.java
Fix population of 18 authority ldr position
If the leader item has multiply possible values then populate the leader with the first possible value if the leader's item is not acceptable.
> MODQM-250 Fix population of 18 authority ldr position

- pom.xml
- src/main/java/org/folio/qm/converter/elements/Constants.java
- src/main/java/org/folio/qm/exception/FieldsValidationException.java
- src/main/java/org/folio/qm/mapper/CreationStatusMapper.java
- src/test/java/org/folio/qm/controller/BaseIT.java
- src/test/java/org/folio/qm/controller/KafkaListenerIT.java
- src/test/java/org/folio/qm/controller/RecordsEditorAsyncIT.java
- src/test/java/org/folio/qm/controller/RecordsEditorIT.java
- src/test/java/org/folio/qm/util/JsonUtilsTest.java
- src/test/java/org/folio/qm/validation/impl/authority/OnlyOne1XXRequiredAuthorityValidationRuleTest.java
Fix integration tests don't run
> Fix integration tests don't run

- src/main/java/org/folio/qm/service/impl/FieldProtectionSetterServiceImpl.java
- src/test/java/org/folio/qm/service/impl/FieldProtectionSetterServiceImplTest.java
Fix issue with MARC field protection subfield verification
JIRA: https://issues.folio.org/browse/MODQM-262
- Fix pattern for subfield verification
- Add tests
> MODQM-262 - MARC field protection doesn't verify the subfield value

- PULL_REQUEST_TEMPLATE.md
- src/main/resources/application-dev.yaml
- src/main/resources/application.yaml
_Logging should be improved for more productive troubleshooting._
- Check that log4j2.properties doesn't exist or it is aligned with https://wiki.folio.org/display/DD/Folio+logging+solution
- Enable the /loggers endpoint in our application.properties file by adding the following lines:
- management.endpoints.web.exposure.include=loggers
- management.endpoint.loggers.enabled=true
- The version of the folio-spring-base should be updated (see [FOLSPRINGB-45](https://issues.folio.org/browse/FOLSPRINGB-45))
- Add step "Check logging" to PULL_REQUEST_TEMPLATE.md
https://issues.folio.org/browse/MODQM-297
> MODQM-297 - Logging configuration

- src/main/java/org/folio/qm/validation/FieldValidationRule.java
- src/main/java/org/folio/qm/validation/impl/authority/OnlyOne010AllowedAuthorityValidationRule.java
- src/test/java/org/folio/qm/validation/impl/authority/OnlyOne010AllowedAuthorityValidationRuleTest.java
- src/test/java/org/folio/qm/validation/impl/authority/OnlyOne010RequiredAuthorityValidationRuleTest.java
_Validate 010 field for duplication._
_New validation added for this purpose_
- There were no big change like permission, API or database changes which may affect versioning.
> MODQM-306 Added validation rule for 010 field

- src/main/java/org/folio/qm/validation/FieldValidationRule.java
- src/test/java/org/folio/qm/controller/RecordsEditorAsyncIT.java
- src/test/java/org/folio/qm/controller/RecordsEditorIT.java
- src/test/java/org/folio/qm/validation/impl/authority/OnlyOne010AllowedAuthorityValidationRuleTest.java
- src/test/java/org/folio/qm/validation/impl/authority/OnlyOne1XxRequiredAuthorityValidationRuleTest.java
- src/test/java/org/folio/qm/validation/impl/holdings/OnlyOne008ControlFieldValidationRuleTest.java
_Omitting actual and potential code smells._
_Created and used String constants to avoid repeated String values._
> MODQM-306 Correction of actual and potential code smells

- README.md
- src/main/java/org/folio/qm/validation/impl/bibliographic/OnlyOne245RequiredBibliographicValidationRule.java
- src/test/java/org/folio/qm/validation/impl/bibliographic/OnlyOne245RequiredHoldingsValidationRuleTest.java
_Do not allow user to remove field 245._
_Validation added to check the field exists_
- There were no big changes related to API, structure or database that affect versioning.
> MODQM-307: 245 MARC bib field validation

- src/main/java/org/folio/qm/service/impl/CleanupServiceImpl.java
- src/main/java/org/folio/qm/service/impl/DataImportEventProcessingServiceImpl.java
- src/main/java/org/folio/qm/service/impl/DeferredResultCacheService.java
- src/main/java/org/folio/qm/service/impl/MarcRecordsServiceImpl.java
- src/main/java/org/folio/qm/service/impl/ValidationServiceImpl.java
- src/main/java/org/folio/qm/util/DataImportEventUtils.java
_Logging improvement for more productive troubleshooting._
_Added logs in branching and conditions_
https://issues.folio.org/browse/MODQM-200
> MODQM-200 - Logging improvement

- .rancher-pipeline.yml
- Dockerfile
- Jenkinsfile
- pom.xml
- src/main/java/org/folio/qm/client/LinksClient.java
- src/main/java/org/folio/qm/client/UsersClient.java
- src/main/java/org/folio/qm/controller/ErrorHandling.java
- src/main/java/org/folio/qm/controller/RecordsEditorApiImpl.java
- src/main/java/org/folio/qm/controller/filter/UserIdOkapiHeaderValidationFilter.java
- src/main/java/org/folio/qm/converter/field/qm/Tag006FieldItemConverter.java
- src/main/java/org/folio/qm/converter/field/qm/Tag007FieldItemConverter.java
- src/main/java/org/folio/qm/converter/field/qm/Tag008AuthorityFieldItemConverter.java
- src/main/java/org/folio/qm/converter/field/qm/Tag008BibliographicFieldItemConverter.java
- src/main/java/org/folio/qm/converter/field/qm/Tag008HoldingsFieldItemConverter.java
- src/main/java/org/folio/qm/domain/entity/JobProfile.java
- src/main/java/org/folio/qm/domain/entity/RecordCreationStatus.java
- src/main/java/org/folio/qm/messaging/listener/QuickMarcEventListener.java
- src/main/resources/application-dev.yaml
- src/main/resources/application.yaml
- src/test/java/org/folio/qm/controller/filter/UserIdOkapiHeaderValidationFilterTest.java
Update the module to Spring boot v3.0.2
Module updated to use java 17 https://issues.folio.org/browse/MODQM-301 and spring boot updated to v3 https://issues.folio.org/browse/MODQM-302
_How does this change fulfill the purpose?_
https://wiki.folio.org/display/TC/JDK+17+and+Java+17
https://wiki.folio.org/pages/viewpage.action?spaceKey=~Taras_Spashchenko&title=Migration+to+Spring+Boot+v3.0.0+How+to
> MODQM-302 Update the module to Spring boot v3.0.2

- pom.xml
- src/main/resources/application-dev.yaml
- src/main/resources/application.yaml
> MODQM-302 minor fixes for spring boot upgrade

- descriptors/ModuleDescriptor-template.json
- Update ModuleDescriptor-template.json
- Update ModuleDescriptor-template.json
> MODQM-319 Removed unneeded fields

- NEWS.md
- README.md
- descriptors/ModuleDescriptor-template.json
- src/main/java/org/folio/qm/client/LinksSuggestionsClient.java
- src/main/java/org/folio/qm/controller/RecordsEditorApiImpl.java
- src/main/java/org/folio/qm/service/MarcRecordsService.java
- src/main/java/org/folio/qm/service/impl/MarcRecordsServiceImpl.java
- src/main/resources/swagger.api/records-editor.yaml
Add 'ignoreAutoLinkingEnabled' to links suggestions endpoint
[MODQM-364](https://issues.folio.org/browse/MODQM-364)
Add 'ignoreAutoLinkingEnabled' to links suggestions endpoint, pass it to mod-entities-links client
> feat(links-suggestions): Add 'ignoreAutoLinkingEnabled' to links suggestions endpoint

- NEWS.md
- pom.xml
- src/main/java/org/folio/qm/domain/entity/JobProfile.java
- src/main/java/org/folio/qm/domain/entity/MarcSpecification.java
- src/main/java/org/folio/qm/domain/entity/RecordCreationStatus.java
Release quick-marc v5.0.1
[MODQM-386](https://issues.folio.org/browse/MODQM-386)
> Tmp release v5.0.1

- NEWS.md
- src/main/java/org/folio/qm/converter/elements/Constants.java
- src/main/java/org/folio/qm/converter/field/dto/CommonDataFieldConverter.java
- src/main/java/org/folio/qm/util/MarcUtils.java
- src/test/java/org/folio/qm/converter/field/dto/CommonDataFieldConverterTest.java
- src/test/java/org/folio/qm/converter/field/qm/CommonFieldItemConverterTest.java
support {dollar} as input for a literal $
- Adjust conversion logic
https://folio-org.atlassian.net/browse/MODQM-256
> feat: support {dollar} as input for a literal $

- src/main/java/org/folio/qm/mapper/LinksSuggestionsMapper.java
- src/test/java/org/folio/qm/mapper/LinksSuggestionsMapperTest.java
Support {dollar} as input for a literal $ on link suggestions
Adjust converters
> feat: support {dollar} as input for a literal $ on link suggestions

- NEWS.md
- docker/docker-compose.yml
- pom.xml
Prepare for next development iteration v5.2.0
> Prepare for next development iteration v5.2.0

- src/main/java/org/folio/qm/config/AppConfig.java
- src/main/java/org/folio/qm/converter/MarcQmToMarcRecordConverter.java
- src/main/java/org/folio/qm/service/impl/ValidationServiceImpl.java
Fix issue when there is no validation issue on relatable 001
Do not use marc4j record for validation as it deduplicate 001 field
> fix(validation): marc4j deduplicate 001 field

- NEWS.md
- pom.xml
Review and cleanup Module Descriptors
Add module descriptor validator plugin
https://folio-org.atlassian.net/browse/MODQM-444
> build: add module descriptor validator plugin

- src/test/java/org/folio/qm/controller/SpecificationKafkaListenerIT.java
- src/test/java/org/folio/qm/service/impl/MarcSpecificationServiceTest.java
_Fix failing tests_
_use latest updates from mod-record-specifications_
[MRSPECS-60](https://folio-org.atlassian.net/browse/MRSPECS-60)
> fix(test): Fix tests failures on dependant DTOs updates

- NEWS.md
- pom.xml
prepare for next development iteration v7.1.0
> chore: prepare for next development iteration v7.1.0

- src/main/java/org/folio/qm/mapper/LinksSuggestionsMapper.java
- src/test/java/org/folio/qm/mapper/LinksSuggestionsMapperTest.java
ignore empty subfields during conversion from DTO for link suggestions
https://folio-org.atlassian.net/browse/MODQM-445
> fix: ignore empty subfields during conversion from DTO for link suggestions
